In [2]:
## Numpy 공부

In [4]:
import numpy as np

In [6]:
array1=np.array([1,2,3])
array1

array([1, 2, 3])

In [11]:
print(f'array1 type: {type(array1)} array1 shape: {array1.shape}')

array1 type: <class 'numpy.ndarray'> array1 shape: (3,)


In [12]:
array2=np.array([[1,2,3],[2,3,4]])
print(f'array2 type: {type(array2)} array2 shape : {array2.shape}')

array2 type: <class 'numpy.ndarray'> array2 shape : (2, 3)


In [13]:
array3=np.array([[1,2,3]])
print(f'array3 type: {type(array3)} array3 shape : {array3.shape}')

array3 type: <class 'numpy.ndarray'> array3 shape : (1, 3)


In [15]:
print(f'array1의 차원은 {array1.ndim}, array2의 차원은 {array2.ndim}, array3의 차원은 {array3.ndim}')

array1의 차원은 1, array2의 차원은 2, array3의 차원은 2


In [18]:
list1=[1,2,3]
print(type(list1))
array1=np.array(list1)
print(type(array1))
print(array1,array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [19]:
list1=[1.0,2,3]
print(type(list1))
array1=np.array(list1)
print(type(array1))
print(array1,array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1. 2. 3.] float64


In [23]:
list1=[1,2, 'test']
print(type(list1))
array1=np.array(list1)
print(type(array1))
print(array1,array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
['1' '2' 'test'] <U11


In [29]:
array_int=np.array([1,2,3])
array_float=array_int.astype('float64')
print(array_float,array_float.dtype)

array_int1=array_float.astype('int32')
print(array_int1,array_int1.dtype)

array_float1=np.array([1.1,2.2,3.3])
array_int2=array_float1.astype('int32')
print(array_int2,array_int2.dtype)

array_str=array_int.astype('U1')
print(array_str,array_str.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32
['1' '2' '3'] <U1


In [31]:
sequence_array=np.arange(10,20,2)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[10 12 14 16 18]
int32 (5,)


In [34]:
zero_array=np.zeros((3,2))
print(zero_array)
print(zero_array.dtype, zero_array.shape)

ones_array=np.ones((3,2))
print(ones_array)
print(ones_array.dtype, ones_array.shape)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
float64 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [36]:
array1=np.arange(10)
print('array1:\n',array1)

array2= array1.reshape(2,5)
print('array2:\n',array2)

array3=array1.reshape(5,-1)
print('array3:\n',array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [38]:
array1=np.arange(8)
array3d=array1.reshape((2,2,2))
print('array3d:\n',array3d.tolist())
print(array3d,array3d.shape)

array5=array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape:',array5.shape)

array6=array1.reshape(-1,1)
print('array6:\n',array6.tolist())
print('array6 shape:',array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]] (2, 2, 2)
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


In [39]:
array1=np.arange(1,10)
print('array1:',array1)

value=array1[2]
print('value:',value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>


In [40]:
print(f'맨뒤의 값 : {array1[-1]}, 맨 뒤에서 두 번째 값 : {array1[-2]}')

맨뒤의 값 : 9, 맨 뒤에서 두 번째 값 : 8


In [41]:
array2d=array1.reshape(3,3)
print(array2d)

print(f'(row=0, col=0) index 가리키는 값: {array2d[0,0]}')
print(f'(row=0, col=1) index 가리키는 값: {array2d[0,1]}')
print(f'(row=1, col=0) index 가리키는 값: {array2d[1,0]}')
print(f'(row=2, col=2) index 가리키는 값: {array2d[2,2]}')
print(f'(row=2, col=2) index 가리키는 값: {array2d[2][2]}')

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9
(row=2, col=2) index 가리키는 값: 9


In [47]:
array3=array1[:3]
array5=array1[3:]
array6=array1[:]
array7=array1[:9]
print(array3)
print(array5)
print(array6)
print(array7)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [48]:
array1d=np.arange(1,10)
array2d=array1d.reshape(3,3)
print(f'array2d:\n {array2d}')

print(f'array2d[0:2, 0:2]\n {array2d[0:2,0:2]}')
print(f'array2d[1:3, 0:3]\n {array2d[1:3,0:3]}')
print(f'array2d[:, :]\n {array2d[:,:]}')
print(f'array2d[:2, 1:]\n {array2d[:2,1:]}')
print(f'array2d[:2, 0]\n {array2d[:2,0]}')
print(f'array2d[0:2, 0:2]\n {array2d[0:2][0:2]}')

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2]
 [[1 2]
 [4 5]]
array2d[1:3, 0:3]
 [[4 5 6]
 [7 8 9]]
array2d[:, :]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:]
 [[2 3]
 [5 6]]
array2d[:2, 0]
 [1 4]
array2d[0:2, 0:2]
 [[1 2 3]
 [4 5 6]]


In [50]:
print(array2d[0])
print(array2d[1])
print(array2d[0].shape, array2d[1].shape)
print(array2d[0].ndim,array2d[1].ndim)

[1 2 3]
[4 5 6]
(3,) (3,)
1 1


In [61]:
array1d=np.arange(1,10)
array2d=array1d.reshape(3,3)

array3= array2d[[0,1],2]
print(f'array2d[[0,1],2] : {array3.tolist()}')

array4 = array2d[[0,1],0:2]
print(f'array2d[[0,1],0:2] : {array4.tolist()}')

array5 = array2d[[0,2]]
print(f'array2d[[0,1]] : {array5.tolist()}')


array2d[[0,1],2] : [3, 6]
array2d[[0,1],0:2] : [[1, 2], [4, 5]]
array2d[[0,1]] : [[1, 2, 3], [7, 8, 9]]


In [63]:
array1d=np.arange(1,10)

array3 = array1d[array1d > 5]

print(array3)

[6 7 8 9]


In [64]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [65]:
array1d%3==0

array([False, False,  True, False, False,  True, False, False,  True])

In [66]:
array1d=np.arange(1,1000)

In [67]:
array4=array1d[array1d%3==0]
print(array4)

[  3   6   9  12  15  18  21  24  27  30  33  36  39  42  45  48  51  54
  57  60  63  66  69  72  75  78  81  84  87  90  93  96  99 102 105 108
 111 114 117 120 123 126 129 132 135 138 141 144 147 150 153 156 159 162
 165 168 171 174 177 180 183 186 189 192 195 198 201 204 207 210 213 216
 219 222 225 228 231 234 237 240 243 246 249 252 255 258 261 264 267 270
 273 276 279 282 285 288 291 294 297 300 303 306 309 312 315 318 321 324
 327 330 333 336 339 342 345 348 351 354 357 360 363 366 369 372 375 378
 381 384 387 390 393 396 399 402 405 408 411 414 417 420 423 426 429 432
 435 438 441 444 447 450 453 456 459 462 465 468 471 474 477 480 483 486
 489 492 495 498 501 504 507 510 513 516 519 522 525 528 531 534 537 540
 543 546 549 552 555 558 561 564 567 570 573 576 579 582 585 588 591 594
 597 600 603 606 609 612 615 618 621 624 627 630 633 636 639 642 645 648
 651 654 657 660 663 666 669 672 675 678 681 684 687 690 693 696 699 702
 705 708 711 714 717 720 723 726 729 732 735 738 74

In [73]:
org_array = np.array([3,1,9,5])
print(f'원본 행렬 : {org_array}')

sort_array = np.sort(org_array)
print(f'정렬된 행렬 : {sort_array}')

sort_array2=org_array.sort()
print(sort_array2)
print(org_array)

원본 행렬 : [3 1 9 5]
정렬된 행렬 : [1 3 5 9]
None
[1 3 5 9]


In [78]:
np.sort(org_array)[::-1]

array([9, 5, 3, 1])

In [81]:
array2d=np.array([[8,12],[7,1]])

print(array2d)

sort_array2d_axis0 = np.sort(array2d, axis=0)
print(sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print(sort_array2d_axis1)

[[ 8 12]
 [ 7  1]]
[[ 7  1]
 [ 8 12]]
[[ 8 12]
 [ 1  7]]


In [83]:
org_array = np.array([3,1,9,5])
org_array.sort()
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print(sort_indices)

<class 'numpy.ndarray'>
[0 1 2 3]


In [84]:
A=np.array([[1,2,3],[4,5,6]])
B=np.array([[7,8],[9,10],[11,12]])

In [85]:
dot_product=np.dot(A,B)
print(dot_product)

[[ 58  64]
 [139 154]]


In [86]:
print(A.shape)
print(B.shape)

(2, 3)
(3, 2)


In [88]:
print(A)
print(np.transpose(A))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
